// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Client$ReactTemplate = require("./Client.bs.js");
var OpenIssueList$ReactTemplate = require("./OpenIssueList.bs.js");
var RepositoryList$ReactTemplate = require("./RepositoryList.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[
              React.createElement("h1", undefined, "Goals 2+3"),
              ReasonReact.element(/* None */0, /* None */0, RepositoryList$ReactTemplate.make(/* array */[])),
              React.createElement("h1", undefined, "Goal 4"),
              ReasonReact.element(/* None */0, /* None */0, OpenIssueList$ReactTemplate.make(/* array */[]))
            ])), "index");

/*  Not a pure module */
