// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_json = require("bs-platform/lib/js/js_json.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Graphql_error = Caml_exceptions.create("OpenIssueList-ReactTemplate.GetOpenIssues.Graphql_error");

var query = "query   {\nrepository(owner: \"facebook\", name: \"reason\")  {\nissues(first: 100, states: OPEN, orderBy: {field: UPDATED_AT, direction: DESC})  {\ntotalCount  \nnodes  {\ntitle  \nupdatedAt  \n}\n}\n}\n}";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match) {
    var value$1 = match[0]["repository"];
    var match$1 = Js_json.decodeNull(value$1);
    var tmp;
    if (match$1) {
      tmp = /* None */0;
    } else {
      var match$2 = Js_json.decodeObject(value$1);
      var tmp$1;
      if (match$2) {
        var value$2 = match$2[0]["issues"];
        var match$3 = Js_json.decodeObject(value$2);
        var tmp$2;
        if (match$3) {
          var value$3 = match$3[0];
          var value$4 = value$3["totalCount"];
          var match$4 = Js_json.decodeNumber(value$4);
          var tmp$3;
          if (match$4) {
            tmp$3 = match$4[0] | 0;
          } else {
            throw Graphql_error;
          }
          var value$5 = value$3["nodes"];
          var match$5 = Js_json.decodeNull(value$5);
          var tmp$4;
          if (match$5) {
            tmp$4 = /* None */0;
          } else {
            var match$6 = Js_json.decodeArray(value$5);
            var tmp$5;
            if (match$6) {
              tmp$5 = match$6[0].map((function (value) {
                      var match = Js_json.decodeNull(value);
                      if (match) {
                        return /* None */0;
                      } else {
                        var match$1 = Js_json.decodeObject(value);
                        var tmp;
                        if (match$1) {
                          var value$1 = match$1[0];
                          var value$2 = value$1["title"];
                          var match$2 = Js_json.decodeString(value$2);
                          var tmp$1;
                          if (match$2) {
                            tmp$1 = match$2[0];
                          } else {
                            throw Graphql_error;
                          }
                          tmp = {
                            title: tmp$1,
                            updatedAt: value$1["updatedAt"]
                          };
                        } else {
                          throw Graphql_error;
                        }
                        return /* Some */[tmp];
                      }
                    }));
            } else {
              throw Graphql_error;
            }
            tmp$4 = /* Some */[tmp$5];
          }
          tmp$2 = {
            totalCount: tmp$3,
            nodes: tmp$4
          };
        } else {
          throw Graphql_error;
        }
        tmp$1 = {
          issues: tmp$2
        };
      } else {
        throw Graphql_error;
      }
      tmp = /* Some */[tmp$1];
    }
    return {
            repository: tmp
          };
  } else {
    throw Graphql_error;
  }
}

function make() {
  return {
          query: query,
          variables: null,
          parse: parse
        };
}

function makeWithVariables() {
  return {
          query: query,
          variables: null,
          parse: parse
        };
}

function ret_type() {
  return /* module */[];
}

var MT_Ret = /* module */[];

var GetOpenIssues = /* module */[
  /* Graphql_error */Graphql_error,
  /* query */query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var GetOpenIssuesQuery = ReasonApollo.CreateQuery([
      query,
      parse
    ]);

var component = ReasonReact.statelessComponent("OpenIssueList");

function make$1() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var reposQuery = make(/* () */0);
              return ReasonReact.element(/* None */0, /* None */0, Curry.app(GetOpenIssuesQuery[/* make */3], [
                              /* Some */[reposQuery.variables],
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              (function (param) {
                                  var result = param[/* result */0];
                                  if (typeof result === "number") {
                                    if (result === 0) {
                                      return React.createElement("div", undefined, "Loading");
                                    } else {
                                      return React.createElement("div", undefined, "No Data");
                                    }
                                  } else if (result.tag) {
                                    var match = result[0].repository;
                                    if (match) {
                                      var repository = match[0];
                                      var match$1 = repository.issues.nodes;
                                      return React.createElement("div", undefined, String(repository.issues.totalCount) + " open issues.", match$1 ? $$Array.map((function (node) {
                                                          if (node) {
                                                            return React.createElement("div", undefined, node[0].title + " - ");
                                                          } else {
                                                            return React.createElement("div", undefined, "Waht?");
                                                          }
                                                        }), match$1[0]) : React.createElement("div", undefined, "No issues"));
                                    } else {
                                      return React.createElement("div", undefined, "Repository does not exist");
                                    }
                                  } else {
                                    return React.createElement("div", undefined, "ERROR");
                                  }
                                })
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.GetOpenIssues = GetOpenIssues;
exports.GetOpenIssuesQuery = GetOpenIssuesQuery;
exports.component = component;
exports.make = make$1;
/* GetOpenIssuesQuery Not a pure module */
